# Generated by Django 6.0.3 on 2026-08-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alias_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reputation_score', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('channel', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ALLOWED', 'Allowed'), ('SIMULATED_HOLD', 'Simulated Hold'), ('FLAGGED', 'Flagged')], default='ALLOWED', max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='api.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('case_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('risk_score', models.IntegerField()),
                ('risk_tier', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('triggered_rules', models.JSONField(default=list)),
                ('ai_explanations', models.JSONField(default=list)),
                ('graph_payload', models.JSONField(default=dict)),
                ('evidence_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cases', to='api.transaction')),
            ],
        ),
    ]
