# Generated by Django 5.2.17 on 2026-08-21 12:44

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    if not User.objects.filter(username="Ashribad2005").exists():
        User.objects.create(
            username="Ashribad2005",
            password=make_password("Ashribad"),
            is_superuser=True,
            is_staff=True,
            is_active=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_channel_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
